### ISSUE TITLE
How can use SetaPDF-Signer-Addon-GlobalSign-DSS module with php 5.6

### ISSUE THREAD

**Issue by rajeshc1988** [Setasign/SetaPDF-Signer-Addon-GlobalSign-DSS#1]
I am using a global sign api.

Please help me, how to use the signature process with PHP 5.3 or PHP 5.6
Because I have a restriction with old running code.

**Comment by JanSlabon** [comment]
This add-on was simply not tested with these (dead) PHP versions, sorry.
Due to the PHPUnit version we need to use we have the constraint to PHP 7.1 and up.

You may try to fork and downgrade the dependencies.

**Comment by rajeshc1988** [comment]
Hi, 

I want implement without using seta pdf module. 
Please help me out

**Comment by JanSlabon** [comment]
Then you're wrong at this repository.
