### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by rajeshc1988** [Setasign/SetaPDF-Signer-Addon-GlobalSign-DSS#2]
Hi,

I am using username and password of setasign but I am facing when running command composer install

- Installing setasign/setapdf-core (2.31.0.1330):
    Authentication required (www.setasign.com):
      Username: rajesh.kumar1@biz2credit.com
      Password:
Downloading (connecting...)

  [Composer\Downloader\TransportException]
  Invalid credentials for 'https://www.setasign.com/downloads/2221236/SetaPDF-Core_2.31.0.1330-without-demos.zip', aborting.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by JanSlabon** [comment]
I just checked your account and you simply do not own a license. You can request an evaluation version [here](https://www.setasign.com/products/setapdf-signer/evaluate/) (make sure you update your dependencies to [this one](https://github.com/Setasign/SetaPDF-Signer-Addon-GlobalSign-DSS#evaluation-version)) or purchase a license [here](https://www.setasign.com/products/setapdf-signer/pricing/).

**Comment by rajeshc1988** [comment]
Hi,

I have done same but facing issues

Fatal error: Uncaught SetaPDF_Signer_Asn1_Exception: Invalid Ident for root element of OCSP response. in E:\xampp\htdocs\Sites\esign\SetaPDF-Signer-Addon-GlobalSign-DSS\vendor\setasign\eval\setapdf-signer\ioncube\php5.6\library\SetaPDF\Signer\Signature\Module\Cms.php:198 Stack trace: #0 E:\xampp\htdocs\Sites\esign\SetaPDF-Signer-Addon-GlobalSign-DSS\vendor\setasign\eval\setapdf-signer\ioncube\php5.6\library\SetaPDF\Signer\Signature\Module\Cms.php(226): SetaPDF_Signer_Signature_Module_Cms->addOcspResponse('MIIF4AoBAKCCBdk...') #1 E:\xampp\htdocs\Sites\esign\SetaPDF-Signer-Addon-GlobalSign-DSS\src\SignatureModule.php(81): SetaPDF_Signer_Signature_Module_Cms->setOcspResponse('MIIF4AoBAKCCBdk...') #2 E:\xampp\htdocs\Sites\esign\SetaPDF-Signer-Addon-GlobalSign-DSS\vendor\setasign\eval\setapdf-signer\ioncube\php5.6\library\SetaPDF\Signer.php(612): setasign\SetaPDF\Signer\Module\GlobalSign\Dss\SignatureModule->createSignature(Object(SetaPDF_Core_Reader_FilePath)) #3 E:\xampp\htdocs\Sites\esign\SetaPDF-Signer-Addon-GlobalSign-DSS in E:\xampp\htdocs\Sites\esign\SetaPDF-Signer-Addon-GlobalSign-DSS\vendor\setasign\eval\setapdf-signer\ioncube\php5.6\library\SetaPDF\Signer\Signature\Module\Cms.php on line 211

**Comment by JanSlabon** [comment]
Thanks for reporting! Fixed via #3.
